/* Generated By:JavaCC: Do not edit this line. ParserGrammarConstants.java */
package src.server.parserjavacc;

public interface ParserGrammarConstants {

  int EOF = 0;
  int TERM = 5;
  int NOTERM = 6;
  int SEP = 7;
  int EPS = 8;
  int SEL = 9;
  int ARROW = 10;
  int END = 11;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<TERM>",
    "<NOTERM>",
    "\"%\"",
    "\"\\u00ca\"",
    "\"|\"",
    "\":\"",
    "\";\"",
    "\"start\"",
  };

}
