function gramaticacs(){var Q='bootstrap',R='begin',S='gwt.codesvr.gramaticacs=',T='gwt.codesvr=',U='gramaticacs',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='Failed to load ',qb='head',rb='meta',sb='name',tb='gramaticacs::',ub='::',vb='gwt:property',wb='content',xb='=',yb='gwt:onPropertyErrorFn',zb='Bad handler "',Ab='" for "gwt:onPropertyErrorFn"',Bb='gwt:onLoadErrorFn',Cb='" for "gwt:onLoadErrorFn"',Db='#',Eb='?',Fb='/',Gb='img',Hb='clear.cache.gif',Ib='baseUrl',Jb='gramaticacs.nocache.js',Kb='base',Lb='//',Mb='locale',Nb='default',Ob='locale=',Pb=7,Qb='&',Rb='__gwt_Locale',Sb='_',Tb='Unexpected exception in locale detection, using default: ',Ub=2,Vb=3,Wb=4,Xb='user.agent',Yb='webkit',Zb='safari',$b='msie',_b=10,ac=11,bc='ie10',cc=9,dc='ie9',ec=8,fc='ie8',gc='gecko',hc='gecko1_8',ic='selectingPermutation',jc='gramaticacs.devmode.js',kc='de',lc='043925C5E044BD083CD1E3AAC39AD956',mc='en',nc='0ABA3CCA0345D74B89F8AD8FC670A2FE',oc='1B41B27717F18575E870D4E9DA9596C3',pc='es',qc='243F941B8F1B485819BBC31890AE5372',rc='261C932DF97E210163586BE2AF3FFB21',sc='2B606617F5A0F0F41453F78608694343',tc='2FE35348CE0FADFED39D6FEFE090BC9D',uc='fr',vc='3CD66BA7A7E095C9DE538CCD41944F6E',wc='3E3DACCB2F9F62A07BED63819F03A4B0',xc='5972D5BFCE9C41ACBA5BDE6482F52A83',yc='59D198D9BD3D6DD0878D2978E1152C7A',zc='64432C16FB694E903A29D28F6C268BC6',Ac='69AC758C83E8F509DF20FBE03A17B106',Bc='79CDBF518EBC9D7B43CC901C5366F539',Cc='8A59E38A11139F7D4F1BC848D4F43871',Dc='8DFDBD04F3FAA9A56CE57DD317876725',Ec='919009B4F94841F75C357F832CB5FBDE',Fc='A243A672DAA1E7BE44C96884EC413445',Gc='A2CAE3A7742BA2F6D4772E8DAF0CEB46',Hc='A64BE7123623F7E5A9FDE0027E74BEF4',Ic='A76DC47E13B7ED2EE0BF6F1DE5DF393F',Jc='AB9F27519CF0AB58CF53EBADFE9218CF',Kc='C2D6018580EC8EDCA636258F8E203F27',Lc='CAD8DA5E2A3DE60A7AAD898E396A940D',Mc='DC465B800008945FB2D502E362461987',Nc=':',Oc='.cache.js',Pc='link',Qc='rel',Rc='stylesheet',Sc='href',Tc='loadExternalRefs',Uc='gwt/clean/clean.css',Vc='/GramaticaCS.css',Wc='end',Xc='http:',Yc='file:',Zc='_gwt_dummy_',$c='__gwtDevModeHook:gramaticacs',_c='Ignoring non-whitelisted Dev Mode URL: ',ad=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
gramaticacs.__sendStats=t;gramaticacs.__moduleName=U;gramaticacs.__errFn=null;gramaticacs.__moduleBase=W;gramaticacs.__softPermutationId=X;gramaticacs.__computePropValue=null;gramaticacs.__getPropMap=null;gramaticacs.__installRunAsyncCode=function(){};gramaticacs.__gwtStartLoadingFragment=function(){return null};gramaticacs.__gwt_isKnownPropertyValue=function(){return false};gramaticacs.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};gramaticacs.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[gramaticacs.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
gramaticacs.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(gramaticacs.__errFn){n.onerror=function(){gramaticacs.__errFn(U,new Error(pb+code))}}r.getElementsByTagName(qb)[X].appendChild(n)}
gramaticacs.__startLoadingFragment=function(a){return G(a)};gramaticacs.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(rb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(sb),k;if(j){j=j.replace(tb,db);if(j.indexOf(ub)>=X){continue}if(j==vb){k=i.getAttribute(wb);if(k){var l,m=k.indexOf(xb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==yb){k=i.getAttribute(wb);if(k){try{d=eval(k)}catch(a){alert(zb+k+Ab)}}}else if(j==Bb){k=i.getAttribute(wb);if(k){try{e=eval(k)}catch(a){alert(zb+k+Cb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;gramaticacs.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Db);if(b==-1){b=a.length}var c=a.indexOf(Eb);if(c==-1){c=a.length}var d=a.lastIndexOf(Fb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Gb);b.src=a+Hb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Ib);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Jb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Kb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Lb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return gramaticacs.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=X){var f=d.substring(e+Pb);var g=d.indexOf(Qb,e);if(g<X){g=d.length}b=d.substring(e+Pb,g)}}if(!b){b=__gwt_getMetaProperty(Mb)}if(!b){b=q[Rb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Mb,b)){var h=b.lastIndexOf(Sb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Tb+a)}q[Rb]=c;return b||Nb};l[Mb]={de:X,'default':Y,en:Ub,es:Vb,fr:Wb};m[Xb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Yb)!=-1}())return Zb;if(function(){return a.indexOf($b)!=-1&&(b>=_b&&b<ac)}())return bc;if(function(){return a.indexOf($b)!=-1&&(b>=cc&&b<ac)}())return dc;if(function(){return a.indexOf($b)!=-1&&(b>=ec&&b<ac)}())return fc;if(function(){return a.indexOf(gc)!=-1||b>=ac}())return hc;return db};l[Xb]={gecko1_8:X,ie10:Y,ie8:Ub,ie9:Vb,safari:Wb};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};gramaticacs.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};gramaticacs.__computePropValue=n;q.__gwt_activeModules[U].bindings=gramaticacs.__getPropMap;t(Q,ic);if(s()){return G(jc)}var o;try{k([kc,Zb],lc);k([mc,Zb],nc);k([kc,dc],oc);k([pc,dc],qc);k([kc,bc],rc);k([Nb,hc],sc);k([pc,fc],tc);k([uc,bc],vc);k([kc,hc],wc);k([kc,fc],xc);k([pc,hc],yc);k([Nb,bc],zc);k([mc,fc],Ac);k([Nb,fc],Bc);k([uc,dc],Cc);k([Nb,Zb],Dc);k([uc,fc],Ec);k([mc,dc],Fc);k([uc,Zb],Gc);k([pc,bc],Hc);k([uc,hc],Ic);k([mc,bc],Jc);k([mc,hc],Kc);k([pc,Zb],Lc);k([Nb,dc],Mc);o=i[n(Mb)][n(Xb)];var p=o.indexOf(Nc);if(p!=-1){j=parseInt(o.substring(p+Y),_b);o=o.substring(X,p)}}catch(a){}gramaticacs.__softPermutationId=j;return G(o+Oc)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Pc);b.setAttribute(Qc,Rc);b.setAttribute(Sc,G(a));r.getElementsByTagName(qb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Tc,R);c(Uc);c(Vc);t(Tc,Wc)}
D();gramaticacs.__moduleBase=F();v[U].moduleBase=gramaticacs.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Xc||q.location.protocol==Yc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Zc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=$c;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(_c+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+ad]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(qb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Wc);C(J);return true}
gramaticacs.succeeded=gramaticacs();