/* Generated By:JavaCC: Do not edit this line. ParserExpRegConstants.java */
package algorithms.regExp.parserjavacc;

public interface ParserExpRegConstants {

  int EOF = 0;
  int SIMB = 3;
  int END = 4;
  int EPSILON = 5;
  int AST = 6;
  int SEL = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<SIMB>",
    "\"$\"",
    "\"\\u00ca\"",
    "\"*\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
  };

}
